# Generated by Django 4.1.13 on 2023-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='place',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
